cargo-features = ["edition2024"]

[package]
name = "tgp-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tgp-rust"
path = "plugins/main.rs"

[dependencies]
lazy_static = "1.4"
maplit = "1.0.2"
once_cell = "1.8.0"
ctor = "0.1.22"