cargo-features = ["edition2024"]

[package]
name = "tgp_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro=true
path= "./lib.rs"

[dependencies]
syn = "2.0.61"
tgp_parse = { path = "../tgp_parse" }

